<a href="https://colab.research.google.com/github/sugimotoh/classes/blob/main/marketingmodels2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###***Part1***###
**code 1-1: Pip Installs Python**

In [1]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ucimlrepo) (2.0.3)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.10/dist-packages (from ucimlrepo) (2024.6.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

code 1-2: scraping data by using ucimlreop

In [2]:
from ucimlrepo import fetch_ucirepo
# fetch dataset
bank_marketing = fetch_ucirepo(id=222)

# data (as pandas dataframes)
X = bank_marketing.data.features
y = bank_marketing.data.targets

# metadata
#print(bank_marketing.metadata)
# variable information
#print(bank_marketing.variables)

code 1-3: check the data X and X head

In [3]:
X

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [4]:
X.head()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN

code 1-4: check the vector y and y head

In [ ]:
y

         y
0       no
1       no
2       no
3       no
4       no
...    ...
45206  yes
45207  yes
45208  yes
45209   no
45210   no

[45211 rows x 1 columns]

###**Part2**###
code 2-1: sample size, the number of records

In [15]:
y.size

45211

code 2-2: 10th to 30th of vector y

In [16]:
y[9:32]

     y
9   no
10  no
11  no
12  no
13  no
14  no
15  no
16  no
17  no
18  no
19  no
20  no
21  no
22  no
23  no
24  no
25  no
26  no
27  no
28  no
29  no
30  no
31  no

code 2-3: filter the variable "age" from matrix X

In [ ]:
X["age"]

0        58
1        44
2        33
3        47
4        33
         ..
45206    51
45207    71
45208    72
45209    57
45210    37
Name: age, Length: 45211, dtype: int64

code 2-4: filter the variables "age", "job","marital" and "education" from matrix X

In [ ]:
X[["age", "education"]]

       age  education
0       58   tertiary
1       44  secondary
2       33  secondary
3       47        NaN
4       33        NaN
...    ...        ...
45206   51   tertiary
45207   71    primary
45208   72  secondary
45209   57  secondary
45210   37  secondary

[45211 rows x 2 columns]

In [ ]:
X[["age", "job","marital","education"]]

       age           job   marital  education
0       58    management   married   tertiary
1       44    technician    single  secondary
2       33  entrepreneur   married  secondary
3       47   blue-collar   married        NaN
4       33           NaN    single        NaN
...    ...           ...       ...        ...
45206   51    technician   married   tertiary
45207   71       retired  divorced    primary
45208   72       retired   married  secondary
45209   57   blue-collar   married  secondary
45210   37  entrepreneur   married  secondary

[45211 rows x 4 columns]

In [ ]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

df = pd.DataFrame(X)

df.to_excel('output.xlsx', index=False)

In [ ]:
X[X["marital"] == "married"]

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
5,35,management,married,tertiary,no,231,yes,no,NaN,5,may,139,1,-1,0,NaN
8,58,retired,married,primary,no,121,yes,no,NaN,5,may,50,1,-1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45204,73,retired,married,secondary,no,2850,no,no,cellular,17,nov,300,1,40,8,failure
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

code 2-5: filter the variables "age", "job","marital" and "education" from matrix X and specifing only "married".

In [17]:
bank_DF=X[X["marital"] == "married"][["age", "job", "marital", "education","housing"]]
bank_DF
#X['marital'] == 'married' #check the function of code

       age           job  marital  education housing
0       58    management  married   tertiary     yes
2       33  entrepreneur  married  secondary     yes
3       47   blue-collar  married        NaN     yes
5       35    management  married   tertiary     yes
8       58       retired  married    primary     yes
...    ...           ...      ...        ...     ...
45204   73       retired  married  secondary      no
45206   51    technician  married   tertiary      no
45208   72       retired  married  secondary      no
45209   57   blue-collar  married  secondary      no
45210   37  entrepreneur  married  secondary      no

[27214 rows x 5 columns]

code 2-6: filter the variables "age", "job","marital" and "education" from matrix X. Specifing only "married" and age=20.

In [9]:
X[(X["marital"] == "married") & (X["age"]==20)] [["age", "job", "marital", "education"]]

       age          job  marital education
4157    20  blue-collar  married   primary
34204   20      student  married       NaN
40647   20      student  married       NaN

code 2-6: filter the variables "age", "job","marital" and "education" from matrix X. Specifing only "married" and 18<=age<23.

In [ ]:
testDF=X[(X["marital"] == "married") & (X["age"]>= 18) & (X["age"]< 23) ] [["age", "job", "marital", "education"]]
testDF

       age          job  marital  education
2345    22     services  married  secondary
3301    21     services  married  secondary
4157    20  blue-collar  married    primary
4258    22  blue-collar  married  secondary
4529    22     services  married  secondary
6248    21  blue-collar  married  secondary
6698    22  blue-collar  married  secondary
8406    21   unemployed  married  secondary
8748    22     services  married    primary
8800    21  blue-collar  married    primary
8818    22       admin.  married  secondary
12338   22  blue-collar  married  secondary
34204   20      student  married        NaN
35126   22  blue-collar  married  secondary
38155   21  blue-collar  married    primary
39288   22     services  married  secondary
40647   20      student  married        NaN

[***2point***]

**Assignment01 make dataframe, variables are "age", "job", "marital", "education", and education is secondary or tertiary.**

In [10]:
import pandas as pd

In [12]:
education_counts = X['education'].value_counts()
education_counts

education
secondary    23202
tertiary     13301
primary       6851
Name: count, dtype: int64

In [13]:
testDF = X[(X["education"] == "tertiary") | (X["education"] == "secondary")][["age", "job", "marital", "education"]]
testDF

       age           job  marital  education
0       58    management  married   tertiary
1       44    technician   single  secondary
2       33  entrepreneur  married  secondary
5       35    management  married   tertiary
6       28    management   single   tertiary
...    ...           ...      ...        ...
45205   25    technician   single  secondary
45206   51    technician  married   tertiary
45208   72       retired  married  secondary
45209   57   blue-collar  married  secondary
45210   37  entrepreneur  married  secondary

[36503 rows x 4 columns]

###**Part3**###
code 3-1: merge dataframes by using pd.merge.

In [24]:
import pandas as pd
df=pd.merge(y, X, right_index=True, left_index=True)
df

,y,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,no,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,no,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,no,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,no,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,no,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,yes,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN
45207,yes,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN
45208,yes,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,no,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN
45210,no,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [28]:
resultDF =df.assign(type='bank-additional-full')
resultDF

,y,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,type
0,no,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,bank-additional-full
1,no,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,bank-additional-full
2,no,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,bank-additional-full
3,no,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,bank-additional-full
4,no,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,bank-additional-full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,yes,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN,bank-additional-full
45207,yes,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN,bank-additional-full
45208,yes,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,bank-additional-full
45209,no,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN,bank-additional-full
45210,no,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,bank-additional-full

In [32]:
import numpy as np
# convert resultDF as dataframe df02
df02 = pd.DataFrame(resultDF)
# add variable "agegroup"
df02['agegroup'] = np.where(df02['age'] >= 50, '50歳以上',
                                        np.where(df02['age'] >= 30, '30歳以上49歳', '29歳以下'))
# convert resultDF
df02= pd.DataFrame(df02)
# show daraframe
df02

,y,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,type,agegroup
0,no,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,bank-additional-full,50歳以上
1,no,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,bank-additional-full,30歳以上49歳
2,no,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,bank-additional-full,30歳以上49歳
3,no,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,bank-additional-full,30歳以上49歳
4,no,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,bank-additional-full,30歳以上49歳
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,yes,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,NaN,bank-additional-full,50歳以上
45207,yes,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,NaN,bank-additional-full,50歳以上
45208,yes,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,bank-additional-full,50歳以上
45209,no,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,NaN,bank-additional-full,50歳以上
45210,no,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,bank-additional-full,30歳以上49歳

[***2point***]

**Assignment02 add new variable "agegroup", age<40 as '40歳未満' and age>39 as '40歳以上', to dataframe df02.**

[***2point***]

**Assignment03 add new variable "conversion", y="no" as '0' and y=1 as '1', to dataframe df02.**

not yet below

In [ ]:
import numpy as np

code_09 ageの合計を計算

In [ ]:
sum(X["age"])

NameError: name 'X' is not defined

In [ ]:
https://plotly.com/python/renderers/
https://colab.research.google.com/github/shibats/minpy_samplecodes_4th/blob/master/Chapter12/12-03.ipynb
https://colab.research.google.com/github/shibats/minpy_samplecodes_4th/blob/master/Chapter12/12-01.ipynb#scrollTo=7LKdq19ICSXe
https://note.com/k_fukunaka/n/nc418095a782e